//
// Created by 19711 on 2024/3/19.
//

#ifndef CPP_HSE_FILTERCONSTANTS_H
#define CPP_HSE_FILTERCONSTANTS_H

const int GAUSSIAN_BLUR_RADIUS = 20;
const int RELIEF_VALUE = 128;
const int MIN_RELIEF_STRENGTH = 1;
const int MAX_RELIEF_STRENGTH = 10;
const double GRAYSCALE_BLUE_PARAMETER = 0.114;
const double GRAYSCALE_GREEN_PARAMETER = 0.587;
const double GRAYSCALE_RED_PARAMETER = 0.299;

#endif  // CPP_HSE_FILTERCONSTANTS_H
